apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: thrift
  selector:
    app: {{ .Values.applicationName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-metrics
  labels:
    app: {{ .Values.applicationName }}
spec:
  ports:
    - name: jmx-metrics
      port: 9404
      targetPort: 9404
      protocol: TCP
  selector:
    app: {{ .Values.applicationName }}